/** @type {import('next').NextConfig} */
const nextConfig = {
  env: {
    NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: process.env.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY,
    NEXT_PUBLIC_SNOWFLAKE_ACCOUNT: process.env.NEXT_PUBLIC_SNOWFLAKE_ACCOUNT,
    NEXT_PUBLIC_SNOWFLAKE_DATABASE: process.env.NEXT_PUBLIC_SNOWFLAKE_DATABASE,
    NEXT_PUBLIC_SNOWFLAKE_PASSWORD: process.env.NEXT_PUBLIC_SNOWFLAKE_PASSWORD,
    NEXT_PUBLIC_SNOWFLAKE_USERNAME: process.env.NEXT_PUBLIC_SNOWFLAKE_USERNAME,
    NEXT_PUBLIC_SNOWFLAKE_WAREHOUSE: process.env.NEXT_PUBLIC_SNOWFLAKE_WAREHOUSE
  }
};

export default nextConfig;
