name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, closed]

env:
  # Setting an environment variable with the value of a configuration variable
  env_var: ${{ vars.ENV_CONTEXT_VAR }}

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - name: Set up Node.js version Scott-1
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Use variables
        run: |
          echo "Maps key is: ${{ vars.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY}}"
          echo "variable from shell environment : $env_var"
      - name: Create .env.local file
        run: |
          echo "NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=${{ secrets.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY }}" >> .env.local
          echo "NEXT_PUBLIC_SNOWFLAKE_ACCOUNT=${{ secrets.NEXT_PUBLIC_SNOWFLAKE_ACCOUNT }}" >> .env.local
          echo "NEXT_PUBLIC_SNOWFLAKE_DATABASE=${{ secrets.NEXT_PUBLIC_SNOWFLAKE_DATABASE }}" >> .env.local
          echo "NEXT_PUBLIC_SNOWFLAKE_PASSWORD=${{ secrets.NEXT_PUBLIC_SNOWFLAKE_PASSWORD }}" >> .env.local
          echo "NEXT_PUBLIC_SNOWFLAKE_USERNAME=${{ secrets.NEXT_PUBLIC_SNOWFLAKE_USERNAME }}" >> .env.local
          echo "NEXT_PUBLIC_SNOWFLAKE_WAREHOUSE=${{ secrets.NEXT_PUBLIC_SNOWFLAKE_WAREHOUSE }}" >> .env.local
          echo "NEXT_PUBLIC_MY_KEY=${{ secrets.NEXT_PUBLIC_MY_KEY }}" >> .env.local
      - name: Install Dependencies Scott-2
        run: npm install
      - name: Build
        run: npm run build
        env: # Add environment variables here
          NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: ${{ vars.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY }}
          NEXT_PUBLIC_SNOWFLAKE_ACCOUNT: ${{ vars.NEXT_PUBLIC_SNOWFLAKE_ACCOUNT }}
          NEXT_PUBLIC_SNOWFLAKE_DATABASE: ${{ vars.NEXT_PUBLIC_SNOWFLAKE_DATABASE }}
          NEXT_PUBLIC_SNOWFLAKE_PASSWORD: ${{ vars.NEXT_PUBLIC_SNOWFLAKE_PASSWORD }}
          NEXT_PUBLIC_SNOWFLAKE_USERNAME: ${{ vars.NEXT_PUBLIC_SNOWFLAKE_USERNAME }}
          NEXT_PUBLIC_SNOWFLAKE_WAREHOUSE: ${{ vars.NEXT_PUBLIC_SNOWFLAKE_WAREHOUSE }}  
          
      - name: Build And Deploy Scott-3
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          echo "Azure API key is: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_KIND_FIELD_0CA5DB30F}}"
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_KIND_FIELD_0CA5DB30F }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_KIND_FIELD_0CA5DB30F }}
          action: "close"